config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  delete '/logout' => 'sessions#destroy'

  resources :dashboard
  resources :employments
  resources :events
  resources :friendships
  resources :profiles
  resources :sessions
  resources :users
  resources :searched

  resources :messages do
    resources :responses
  end

end

app/models/employment.rb
class Employment < ActiveRecord::Base
  belongs_to :profile
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
  has_many :messages
  has_many :events
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :friendship
  belongs_to :user

  # takes the time created_at and converts it into a readable date and time
  def created
   created_at.strftime('%m-%d-%Y %I:%M')
    
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # attr_accessible :city, :firstname, :lastname, :role

  belongs_to :user
  has_many :employments
  has_many :messages

  def full_name 
    "#{firstname} #{lastname}"
  end


  def self.search(search)
    if search
      where('city ILIKE ? OR firstname ILIKE ? OR lastname ILIKE ? OR role ILIKE ? OR company ILIKE?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      all
    end
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :message
  
  default_scope {order('created_at DESC')}

  # takes the time created_at and converts it to pacific standard time and then into a readable date and time
  def created
   created_at.in_time_zone("Pacific Time (US & Canada)").strftime('%m-%d-%Y %I:%M') 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :profile
  has_many :friendships
  has_many :friends, :through => :friendships, :class_name => "User"
  has_many :messages
  has_many :events
  # attr_accessor :email, :password, :password_confirmation
  validates_uniqueness_of :email
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
  end

  def edit
  end

  def destroy
  end

  def show
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include ProfilesHelper

  helper_method :sort_column, :sort_direction

  def index
    # @user = User.find(session[:user_id])
    # @profile = @user.profile
    
    if params[:search]
      @profiles = Profile.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 15, :page => params[:page])
    else
      @profiles = Profile.all.order(sort_column + " " + sort_direction).paginate(:per_page => 15, :page => params[:page])
    end
  end

  def show
    # @user = User.find(session[:user_id])
    # @profile = @user.profile
    @messages = Message.all
    @profile=Profile.find(params[:id])
    @current_user = current_user
    @friendships = Friendship.all
    @profiles = Profile.all
    @users = User.all
    render :show
  end

  def new
    @profile = Profile.new
    render :new
  end

  def create
    profile_params = params.require(:profile).permit(:user_id, :firstname, :lastname, :role, :city, :state, :linkedin, :image, :bio, :seeker, :company, :department, :skills)
    @profile = Profile.create(profile_params)
    add_default_image @profile
    render :new
  end

  def edit
    @user = User.find(session[:user_id])
    @profile = @user.profile
    render :edit
  end

  def update
    @profile = Profile.find(params[:id])
    updated_attributes = params.require(:profile).permit(:user_id, :firstname, :lastname, :role, :city, :state, :linkedin, :image, :bio, :seeker, :company, :department, :skills)
    @profile.update_attributes(updated_attributes)
    add_default_image @profile
    redirect_to @profile
  end

  def destroy
    Profile.destroy(params[:id])
    redirect_to "/"
  end

  private

  def sort_column
    Profile.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# GET users/
  def index
    @users = User.all
    render :index
  end

# GET /users/id
  def show
  end

# GET /users/new
# creates user
  def new
    @user = User.new
  end

# POST /users
# saves user
  def create
    @user = User.new(user_params)
    @current_user = current_user
    if @user.save
      login(@user)
      create_profile @current_user.id
      add_default_image @user.profile
      redirect_to dashboard_index_path
    else
      render "new"
    end
  end

# GET /users/id/edit
  def edit
  end

# PATCH/PUT /users/id
  def update
  end

# DELETE /users/id
  def destroy
  end

  def create_profile user_id
    Profile.create(user_id: user_id)
  end

# make it private
  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.new
    @current_user = current_user
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      login(user)
      redirect_to dashboard_index_path
    else
      flash.now.alert = "Email or password not recognized"
      
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def friend_request_accept
    # accepting a friend request is done by the recipient of the friend request.
    # thus the current user is identified by friend_id.
    friendship = Friendship.find(params[:id])
    friendship.update_attributes(status: 'confirm')
  end

  # def friend_delete
  #   friendship = Friendship.where(friend_id: current_user.id, user_id: params[:id]).first
  #   friendship.destroy
  # end

  def friend_request 
    @friendship.update_attribute(:status,'pending')
  end

  def friend_request_ignore
    friendship = Friendship.find(params[:id])
    @friendship.update_attribute(:status, 'ignore')
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

  def add_default_image profile
    profile.image = "profiledefault.jpg" if profile.image.blank?
    profile.save
  end
  
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/searched_helper.rb
module SearchedHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    session[:used_id] = user.id
    @current_user = user
  end

  def logged_in?
    if current_user == nil
    else
      true
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def current_user 
    @current_user ||= session[:user_id] && User.find(session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def friend_request
    user_id = current_user.id
    friend_id = params[:id] # this is the id of the user you want to become friend with
    friendship = Friendship.create(user_id: user_id, friend_id: friend_id, status: false)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/profiles/_profiles.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @profiles %>

app/views/profiles/destroy.html.erb
<section>
  <div class="container">
    <h1>Profiles#destroy</h1>
    <p>Find me in app/views/profiles/destroy.html.erb</p>
  
  </div>
</section>

app/views/profiles/edit.html.erb
<!-- if current user is a candidate -->
<% if current_user.profile.seeker == 'candidate' %>
<section>
  <div class="container compress">
    <div class="row">
      <div class="col-xs-12">
        <h1 class="center">Edit Candidate Profile</h1>
      </div>
    </div>
    <div class="row push-down">
      <div class="col-xs-4 center">
          <% if current_user.profile.seeker == 'candidate' ||  current_user.profile.seeker == 'sourcer'%>
          <%= image_tag @profile.image, class:"profile-image", id:"edit-image" %>
          <%else%>
          <img class="welcome-icon" src="<%= asset_path( 'placeholder-user-photo.png' ) %>" alt="Users icon" width="100px" height="100px"/>
          <h6>Please update your profile image.</h6>
          <%end%>
          <%= form_for @profile do |p| %>
          <%= p.label "Image url" %>
          <%= p.text_field :image, placeholder: "Find a picture you like, right click and hit copy image url", class:'form-control'%>
          <br>
      </div>
      <div class="col-xs-8 center seeker">
        <h4><%= p.label "Status" %></h4>
        <p>Candidate     <%= p.radio_button :seeker, "candidate", :value => "candidate" %></p>
        <p>Sourcer     <%= p.radio_button :seeker, "sourcer", :value => "sourcer" %>
        <br></p>
    </div><!-- end row -->
  </div>
  <div class="row"> <!-- start remaining form fields -->
      <div class="col-xs-4">
        <%= p.label "First name" %>
        <%= p.text_field :firstname, placeholder: "First Name", class:'form-control', autofocus: true %>
        <br>
      </div>
      <div class="col-xs-4">
        <%= p.label "Last name" %>
        <%= p.text_field :lastname, placeholder: "Last Name", class:'form-control' %>
        <br>
      </div>
      <div class="col-xs-4">
        <%= p.label "Linkedin" %>
        <%= p.text_field :linkedin, placeholder: "url to your linked in profile", class:'form-control' %>
        <br>
      </div>
  </div><!-- end row -->
  <div class="row"> <!-- start remaining form fields -->
    <div class="col-xs-4">
        <%= p.label "Desired role" %>
        <%= p.text_field :role, placeholder: "Your Role desired/job title", class:'form-control'%>
        <br>
    </div>
    <div class="col-xs-4">
        <%= p.label "City" %>
        <%= p.text_field :city, placeholder: "City", class:'form-control'%>
        <br>
    </div>
    <div class="col-xs-4">
        <%= p.label "State" %>
        <%= p.text_field :state, placeholder: "State", class:'form-control' %>
        <br>
      </div>
    </div><!-- end row -->
  <div class="row">
    <div class="col-xs-12">
        <%= p.label "Bio" %>
        <%= p.text_area :bio, placeholder: "Short Bio about yourself", class:'form-control' %>
        <br>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
        <%= p.label "Skills" %>
        <%= p.text_area :skills, placeholder: "list or describe your skill sets", class:'form-control' %>
        <br>
    </div>
  </div>
  <div class="row rig">
    <div class="col-xs-6 left">
      <%= link_to "Cancel", profile_path, class: 'btn btn-cancel' %>
    </div>
    <div class="col-xs-6 right">
      <%= p.submit "Update", class: 'btn btn-primary' %>
    </div>
    <% end %>
  </div>
  </div>
</section>

<!-- if current user is a sourcer -->
<% elsif current_user.profile.seeker == 'sourcer' %>
<section>
  <div class="container compress">
    <div class="row">
      <div class="col-xs-12">
        <h1 class="center">Edit Sourcer Profile</h1>
      </div>
    </div>
    <div class="row push-down">
      <div class="col-xs-4 center">
          <% if current_user.profile.seeker == 'candidate' ||  current_user.profile.seeker == 'sourcer'%>
          <%= image_tag @profile.image, class:"profile-image", id:"edit-image" %>
          <%else%>
          <img class="welcome-icon" src="<%= asset_path( 'placeholder-user-photo.png' ) %>" alt="Users icon" width="100px" height="100px"/>
          <h6>Please update your profile image.</h6>
          <%end%>
          <%= form_for @profile do |p| %>
          <%= p.label "Image url" %>
          <%= p.text_field :image, placeholder: "Find a picture you like, right click and hit copy image url", class:'form-control'%>
          <br>
      </div>
      <div class="col-xs-8 center seeker">
        <h4><%= p.label "Status" %></h4>
        <p>Candidate     <%= p.radio_button :seeker, "candidate", :value => "candidate" %></p>
        <p>Sourcer     <%= p.radio_button :seeker, "sourcer", :value => "sourcer" %>
        <br></p>
    </div><!-- end row -->
  </div>
  <div class="row"> <!-- start remaining form fields -->
      <div class="col-xs-4">
        <%= p.label "First name" %>
        <%= p.text_field :firstname, placeholder: "First Name", class:'form-control', autofocus: true %>
        <br>
      </div>
      <div class="col-xs-4">
        <%= p.label "Last name" %>
        <%= p.text_field :lastname, placeholder: "Last Name", class:'form-control' %>
        <br>
      </div>
      <div class="col-xs-4">
          <%= p.label "City" %>
          <%= p.text_field :city, placeholder: "City", class:'form-control'%>
          <br>
      </div>
  </div><!-- end row -->
  <div class="row"> <!-- start remaining form fields -->
    <div class="col-xs-8">
      <%= p.label "Current Job Title" %>
      <%= p.text_field :role, placeholder: "Your Current Job Title", class:'form-control'%>
      <br>
    </div>
    <div class="col-xs-4">
        <%= p.label "State" %>
        <%= p.text_field :state, placeholder: "State", class:'form-control' %>
        <br>
    </div>
  </div><!-- end row -->

  <div class="row"> 
    <div class="col-xs-8">
      <%= p.label "Current Company" %>
      <%= p.text_field :company, placeholder: "The Name of your Current Employer", class:'form-control'%>
      <br>
    </div>
    <div class="col-xs-4">
        <%= p.label "Department" %>
        <%= p.select :department, ['Sales', 'HR/Talent', 'Acquisition', 'Engineering/Development', 'Operations', 'Product Design', 'Marketing', 'Finance/Accounting'], include_blank: true, :class => 'drop' %>
        <br>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
        <%= p.label "Ideal Candidate" %>
        <%= p.text_area :bio, placeholder: "This should describe the ideal candidate, including skills", class:'form-control' %>
        <br>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <%= p.label "Linkedin" %>
      <%= p.text_field :linkedin, placeholder: "url to your linked in profile", class:'form-control' %>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 left">
      <%= link_to "Cancel", profile_path, class: 'btn btn-cancel' %>
    </div>
    <div class="col-xs-6 right">
      <%= p.submit "Update", class: 'btn btn-primary' %>
    </div>
    <% end %>
  </div>
  </div>
</section>

<!-- if current user has not identified as a sourcer or candidate -->
<% else %>
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12"></div>
      <h1 class="center seeker-new">Seeker Status &#38; Basic Info</h1>
    </div>
    <div class="row seeker-new">
      <div class="col-xs-6">
        <%= form_for @profile do |p| %>
        <h3 class="question"><%= p.label "what type of seeker are you?" %></h3>
        <h3>Candidate  <%= p.radio_button :seeker, "candidate", :value => "candidate" %></h3>
        <h3>Sourcer   <%= p.radio_button :seeker, "sourcer", :value => "sourcer" %></h3>
        <br></p>
      </div><!-- end row -->
      <div class="col-xs-6"> <!-- start remaining form fields -->
        <div class="text-right">
          <%= p.submit "Add to Profile", class: 'btn btn-danger add-seeker-status' %>
        </div>
      </div>
    </div>
    <div class="row seeker-new basic">
      <div class="col-xs-6">
        <%= p.label "First name" %>
        <%= p.text_field :firstname, placeholder: "First Name", :required => true, class:'form-control', autofocus: true %>
      </div><!-- end row -->
      <div class="col-xs-6"> <!-- start remaining form fields -->
        <%= p.label "Last name" %>
        <%= p.text_field :lastname, placeholder: "Last Name", :required => true, class:'form-control' %>
      </div>
    </div>
    <div class="row seeker-new basic">
      <div class="col-xs-6">
        <%= p.label "City" %>
        <%= p.text_field :city, placeholder: "City", :required => true, class:'form-control'%>
      </div><!-- end row -->
      <div class="col-xs-6"> <!-- start remaining form fields -->
        <%= p.label "State" %>
        <%= p.text_field :state, placeholder: "State", :required => true, class:'form-control'%>
      </div>
    </div>
  </div>
<% end %>
</section>
<% end %>

app/views/profiles/index.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-3 center searchnav">
        <h4>Search by Keyword</h4><br>
        <%= form_tag profiles_path, :method => 'get', :id => "profiles_search" do %>
          <%= hidden_field_tag :direction, params[:direction] %>
          <%= hidden_field_tag :sort, params[:sort] %>

          <p>
            <%= text_field_tag :search, params[:search], placeholder: "Search Profiles", class: "form-group" %>
          </p>
          <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>

        <% end %>
      </div>
      <div class="col-xs-9">
        <div id="profiles"><%= render 'profiles' %></div>

            <table class="table thumbnail left" width:"100%">
              <tr>
                <th></th>
                <th><%= sortable 'firstname' %></th>
                <th><%= sortable 'lastname' %></th>
                <th><%= sortable 'city' %></th>
                <th><%= sortable 'role' %></th>
                <th><%= sortable 'company' %></th>
              </tr>
              <% if current_user.profile.seeker == 'candidate' %>
                <% for profile in @profiles.where(seeker: "sourcer") %>
                  <tr>
                    <td>
                      <%= link_to profile_path(profile) do%>
                      <img src="<%=profile.image %>">
                      <% end %>
                    </td>
                    <td>
                      <%= link_to profile_path(profile) do%>
                      <%=profile.firstname%>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to profile_path(profile) do%>
                      <%=profile.lastname%>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to profile_path(profile) do%>
                      <%=profile.city%>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to profile_path(profile) do%>
                      <%=profile.role%>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to profile_path(profile) do%>
                      <%=profile.company%>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to "Connect", friendships_path(:friend_id => profile.user), :method => :post, class:"btn btn-primary search" %>
                      <br>
                      <%= link_to "View Profile", profile_path(profile), class:"btn btn-danger search" %>
                    </td>
                  </tr >
                <%end%>
              <% elsif current_user.profile.seeker == 'sourcer' %>
                <% for profile in @profiles.where(seeker: "candidate") %>
                  <tr>
                    <td>
                      <%= link_to profile_path(profile) do%>
                      <img src="<%=profile.image %>">
                      <% end %>
                    </td>
                    <td>
                      <%= link_to profile_path(profile) do%>
                      <%=profile.firstname%>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to profile_path(profile) do%>
                      <%=profile.lastname%>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to profile_path(profile) do%>
                      <%=profile.city%>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to profile_path(profile) do%>
                      <%=profile.role%>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to "Connect", friendships_path(:friend_id => profile.user), :method => :post, class:"btn btn-primary search" %>
                      <br>
                      <%= link_to "View Profile", profile_path(profile), class:"btn btn-danger search" %>
                    </td>
                  </tr >
                <%end%>
              <% end %>
            </table>
            <%= will_paginate @profiles %>
      </div>

    </div>


  </div>
</section>

app/views/profiles/index.js.erb
$("#products").html("<%= escape_javascript(render('profiles')) %>");

app/views/profiles/new.html.erb
<section>
  <div class="container">
    <div class="col-xs-8 col-xs-offset-2">
      <h1>Sign up for Our AMAZING Cool APP!!!</h1>
      <%= form_for @profile do |p| %>
        <%= p.label :firstname %> 
        <%= p.text_field :firstname, placeholder: "First Name", class:'form-control', autofocus: true %> 
        <br>
        <%= p.label :lastname %> 
        <%= p.text_field :lastname, placeholder: "Last Name", class:'form-control' %> 
        <br> 
        <%= p.label :address %>
        <%= p.text_field :address, placeholder: "Street Number and Street", class:'form-control'%> 
        <br> 
        <%= p.label :city %>
        <%= p.text_field :city, placeholder: "City", class:'form-control'%> 
        <br> 
        <%= p.label :state %> 
        <%= p.text_field :state, placeholder: "State", class:'form-control' %> 
        <br> 
        <%= p.label :phone %> 
        <%= p.text_field :phone, placeholder: "Phone Number", class:'form-control' %> 
        <br> 
        <%= p.label :bio %> 
        <%= p.text_area :bio, placeholder: "Short Bio about yourself", class:'form-control' %> 
        <br> 
        <%= p.label :image %>
        <%= p.text_field :image, placeholder: "Find a picture you like, right click and hit copy image url", class:'form-control'%> 
        <br> 
        <div class="text-right">
          <%= p.submit "Create", class: 'btn btn-primary' %> 
        </div>
        <% end %>
      
    </div>
    
  </div>  
</section>

app/views/profiles/show.html.erb
<!-- condition showing of profile -->
<% if @profile.seeker == 'candidate' %>
  <!-- if profile belongs to a candidate,  -->
  <section>
    <div class="container compress">
      <div class="row">
        <div id="profileside" class="col-xs-4 center profile-image">
            <%= image_tag @profile.image, class:"profile-image" %>
        </div>
        <div class="col-xs-6 left name-title">
          <% if @profile.full_name.blank? %>
          <h2>Please update name</h2>
          <%else%>
          <h3 class="name"><%= "#{@profile.full_name}"%></h3>
          <h3 class="title"><%= "#{@profile.role}" %></h3>
          <%end%>
        </div>
      <div class="col-xs-2 center add-friend">
      <% if session[:user_id] != @profile.user.id %>

        <!-- if user is not firends offer creation of friendship -->
        <% for friendship in Friendship.where.not(status: ["confirm", "pending", "ignore"]).where.not('(friend_id=?) OR (user_id=?)', current_user.id, current_user.id).where.not('(friend_id=?) OR (user_id=?)', @profile.user_id, @profile.user_id) %>
          <%= link_to "Connect", friendships_path(:friend_id => @profile.user.id), :method => :post, class:"btn btn-danger " %>
        <% end %>

        <!--  if user is already friends alert already friends  -->
        <% for friendship in Friendship.where(status: "pending", friend_id: @current_user.id, user_id: @profile.user_id) %>
          <p>They have requested a connection that is waiting for approval. Please see your notifications.</p>
        <% end %>
        <% for friendship in Friendship.where(status: "pending", friend_id: @profile.user_id, user_id: @current_user.id) %>
          <p>your requested connection is waiting for approval</p>
        <% end %>
        <% for friendship in Friendship.where(status: "confirm").where('(friend_id=?) OR (user_id=?)', current_user.id, current_user.id).where('(friend_id=?) OR (user_id=?)', @profile.user_id, @profile.user_id) %>
          <p>you are already connected</p>
          <% for message in Message.where(friendship_id: friendship) %>
          <!-- <p><%=message.id%></p> -->
          <%end%>
        <% end %>
        
        

        <% else %>
         <%= button_to "Edit Profile", edit_profile_path, class:"btn btn-danger", method: :get %>
        <%end%>
      </div>
    </div><!-- end row -->
    <div class="row">
      <div class="col-xs-12 location">
        <h4>
          <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
          <%= "#{@profile.city} #{","} #{@profile.state}" %>
        </h4>
      </div>
    </div><!-- end row -->
    <div class="row">
      <div class="col-xs-12">
        <h3>Skills</h3>
      </div>
    </div><!-- end row -->
      <div class="row">
        <div class="col-xs-12 employments indent">
          <p class="e"><%=@profile.skills%></p>
        </div>
      </div>
      <div class="row">
      <div class="col-xs-12">
        <h3>Bio</h3>
      </div>
    </div><!-- end row -->
      <div class="row">
        <div class="col-xs-12 employments indent">
          <p class="e"><%=@profile.bio%></p>
        </div>
      </div><!-- end row -->
      <div class="row ">
        <div class="col-xs-12">
          <h3>Employment History</h3>
        </div>
      </div><!-- end row -->
      <div class="row">
        <% @profile.employments.each do |e| %>
        <div class="row employments industry">
          <div class="indent result-detail">
            <div class="col-xs-8">

            <%= link_to employment_path(e) do%>
            <h4><%=e.title%> at:</h4>
            <!-- <div class="row"> -->
              <h4><%= e.company %></h4>

              <!-- <div class="col-xs-8"> -->
                <h5>Location: <%=e.city%>, <%= e.state %></h5>
                <h5>Industry: <%=e.industry %></h5>
                <%= link_to employment_path(e) do%>
                <h5>Summary: <%=e.summary%></h5>
                <% end %>
              </div>

              <div class="col-xs-4">
                <% if session[:user_id] == @profile.user.id %>
                <%= link_to "Edit this Job", edit_employment_path(e), class:"btn btn-danger pull-right", id:"show-edit" %>
                <% end %>
              </div>
            </div>
            <!-- end row -->
            <% end %>
          </div>
          <%end%>
        </div><!-- end row employments industry -->
          <div class="row">
            <div class="col-xs-12 center">
              <% if session[:user_id] == @profile.user.id %>
                <%= link_to "Add Employment", new_employment_path, class:"btn btn-primary pull-right", id:"show" %>
              <% end %>
            </div>
        </div>
      </div>
</section>
<% elsif @profile.seeker == 'sourcer' %>
  <!-- if profile belongs to a sourcer,  -->
  <section>
    <div class="container compress">
      <div class="row">
        <div id="profileside" class="col-xs-4 center profile-image">
            <%= image_tag @profile.image, class:"profile-image" %>
        </div>
        <div class="col-xs-6 left name-title">
          <% if @profile.full_name.blank? %>
          <h2>Please update name</h2>
          <%else%>
          <h3 class="name"><%= "#{@profile.full_name}"%></h3>
          <h3 class="title"><%= "#{@profile.role}" %></h3>
          <%end%>
        </div>
      <div class="col-xs-2 center add-friend">
        <% if session[:user_id] != @profile.user.id %>
          <%= link_to "Connect", friendships_path(:friend_id => @profile.user.id), :method => :post, class:"btn btn-danger " %>
        <!-- TODO if user is already friends alert already friends  -->
        <!-- if user is not firends offer creation of friendship -->
        <%else%>
         <%= button_to "Edit Profile", edit_profile_path, class:"btn btn-danger", method: :get %>
        <%end%>
      </div>
    </div><!-- end row -->

    <div class="row">
      <div class="col-xs-12 company">
        <h4>Current Company:
        <%= @profile.company %></h4>
        <h5>Department: <%=@profile.department %></h5>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 location">
        <h4>
          <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
          <%= "#{@profile.city} #{","} #{@profile.state}" %>
        </h4>
      </div>
    </div><!-- end row -->
    <div class="row">
      <div class="col-xs-12">
        <h3>Ideal Candidate:</h3>
        <p class="e"><%=@profile.bio%></p>
      </div>
    </div><!-- end row -->
    </div>
  </section>
<% else %>
<!-- if profile belongs to someone who hasn't filled this section out, don't display content,  -->
  <section>
    <!-- if profile belongs to the current user and has not filled out the seeker field, they see this message -->
      <% if current_user.id = @profile.user.id %>
     <div class="row">
       <div class="col-xs-12 center">
         <section>
            <div class="pending-seeker-status">
               <h1>To continue, please update your profile and select whether you are a sourcer or candidate.</h1>
               <%= button_to "Update Profile", edit_profile_path(@current_user.profile), id:"edit-profile", class:"btn btn-primary", method: :get %>
            </div>
         </section>
        <% end %>
      </div>
    </div>
  </section>
<% end %>