config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  delete '/logout' => 'sessions#destroy'

  resources :dashboard
  resources :employments
  resources :events
  resources :friendships
  resources :profiles
  resources :sessions
  resources :users
  resources :searched

  resources :messages do
    resources :responses
  end

end

app/models/employment.rb
class Employment < ActiveRecord::Base
  belongs_to :profile
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
  has_many :messages
  has_many :events
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :friendship
  belongs_to :user

  # takes the time created_at and converts it into a readable date and time
  def created
   created_at.strftime('%m-%d-%Y %I:%M')
    
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # attr_accessible :city, :firstname, :lastname, :role

  belongs_to :user
  has_many :employments
  has_many :messages

  def full_name 
    "#{firstname} #{lastname}"
  end


  def self.search(search)
    if search
      where('city ILIKE ? OR firstname ILIKE ? OR lastname ILIKE ? OR role ILIKE ? OR company ILIKE?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      all
    end
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :message
  
  default_scope {order('created_at DESC')}

  # takes the time created_at and converts it to pacific standard time and then into a readable date and time
  def created
   created_at.in_time_zone("Pacific Time (US & Canada)").strftime('%m-%d-%Y %I:%M') 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :profile
  has_many :friendships
  has_many :friends, :through => :friendships, :class_name => "User"
  has_many :messages
  has_many :events
  # attr_accessor :email, :password, :password_confirmation
  validates_uniqueness_of :email
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
  end

  def edit
  end

  def destroy
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# GET users/
  def index
    @users = User.all
    render :index
  end

# GET /users/id
  def show
  end

# GET /users/new
# creates user
  def new
    @user = User.new
  end

# POST /users
# saves user
  def create
    @user = User.new(user_params)
    @current_user = current_user
    if @user.save
      login(@user)
      create_profile @current_user.id
      add_default_image @user.profile
      redirect_to dashboard_index_path
    else
      render "new"
    end
  end

# GET /users/id/edit
  def edit
  end

# PATCH/PUT /users/id
  def update
  end

# DELETE /users/id
  def destroy
  end

  def create_profile user_id
    Profile.create(user_id: user_id)
  end

# make it private
  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.new
    @current_user = current_user
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      login(user)
      redirect_to dashboard_index_path
    else
      flash.now.alert = "Email or password not recognized"
      
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def friend_request_accept
    # accepting a friend request is done by the recipient of the friend request.
    # thus the current user is identified by friend_id.
    friendship = Friendship.find(params[:id])
    friendship.update_attributes(status: 'confirm')
  end

  # def friend_delete
  #   friendship = Friendship.where(friend_id: current_user.id, user_id: params[:id]).first
  #   friendship.destroy
  # end

  def friend_request 
    @friendship.update_attribute(:status,'pending')
  end

  def friend_request_ignore
    friendship = Friendship.find(params[:id])
    @friendship.update_attribute(:status, 'ignore')
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

  def add_default_image profile
    profile.image = "profiledefault.jpg" if profile.image.blank?
    profile.save
  end
  
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/searched_helper.rb
module SearchedHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    session[:used_id] = user.id
    @current_user = user
  end

  def logged_in?
    if current_user == nil
    else
      true
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def current_user 
    @current_user ||= session[:user_id] && User.find(session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def friend_request
    user_id = current_user.id
    friend_id = params[:id] # this is the id of the user you want to become friend with
    friendship = Friendship.create(user_id: user_id, friend_id: friend_id, status: false)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<section>
  <div class="jumbotron">
    <h1>Your source for qualified candidates</h1>
  </div>
  <div id="welcome" class="container">
    <div id="outline">
      <div class="row">
        <div class="col-xs-6 middle-line center">
          <img class="welcome-icon" src="<%= asset_path( 'sourcer-icon.png' ) %>" alt="Sourcer icon" width="72px" height="74px"/>
          <h2 class="welcome-info">Find Someone to Refer</h2>
          <p class="info-text" align="left">Have a simple informational interview over lunch and refer qualified candidates. Grow your network, build relationships, create great teams, &#38; get referral bonuses.</p>
        </div>
        <div class="col-xs-6 middle-adjust center">
          <img class="welcome-icon" src="<%= asset_path( 'candidate-icon2.png' ) %>" alt="Candidate icon" width="72px" height="74px"/>
          <h2 class="welcome-info">Get a Referral</h2>
          <p class="info-text" align="left">Getting a phone screen or interview without knowing someone at a company can be a duanting task. Referrals are the proven way to make sure your application is reviewed.</p>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 center">
          <!-- Button trigger sign up modal -->
          <% if logged_in? %>
          <a class="btn btn-primary" href="/dashboard/">Go to Dashboard</a>
          <% else %>
          <button data-toggle="modal" data-target="#createUser" id="sign-up">Sign-Up</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div id="more-info" class="container parent">
    <div class="row">
      <div class="col-xs-12 center">
        <h2 id="how-to" class="center">How it Works</h2>
      </div>
    <div class="row">
      <div class="col-sm-4 center">
        <img class="welcome-icon" src="<%= asset_path( 'red-setting2.png' ) %>" alt="Settings icon" width="100px" height="100px"/>
        <h2 class="welcome-info">Filter Results</h2>
        <p class="info-text" align="justify">Filter by location, company, name, role, and department to get the best matches.</p>
      </div>
      <div class="col-sm-4 center">
        <img class="welcome-icon" src="<%= asset_path( 'red-calendar2.png' ) %>" alt="Calendar icon" width="100px" height="100px"/>
        <h2 class="welcome-info">Request a Meeting</h2>
        <p class="info-text" align="justify">Request a meeting with one click. If they agree, you'll set a time to meet.</p>
      </div>
      <div class="col-sm-4 center">
        <img class="welcome-icon" src="<%= asset_path( 'red-users.png' ) %>" alt="Users icon" width="100px" height="100px"/>
        <h2 class="welcome-info">Grow Your Network</h2>
        <p class="info-text" align="justify">Make new connections, build your network, grow relationships, and build great teams.</p>
      </div>
    </div>
  </div>

  <!-- Sign Up Modal -->
  <div class="modal fade" id="createUser" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Sign up</h4>
        </div>
        <div class="modal-body">
          <%= form_for(@user) do |f| %>
            <% if @user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
                <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

              <%= f.label :email %><br>
              <%= f.text_field :email %>
              </br>
              <%= f.label :password %><br>
              <%= f.password_field :password %>
              </br>
              <%= f.label :password_confirmation %><br>
              <%= f.password_field :password_confirmation %>
              </br>
              <%= f.submit %>
              </br>
          <% end %>
        </div>
        <div class="modal-footer">
        <button class="btn btn-success"
            data-toggle="modal" data-target="#logUser" data-dismiss="modal">Log In</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Login Modal -->
  <div class="modal fade" id="logUser" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Log In</h4>
        </div>
        <div class="modal-body">
          <%= form_tag sessions_path, method: :post do %>
            <div class="field">
              <%= text_field_tag :email, nil, placeholder: 'e-mail' %>
            </div></br>
            <div class="field">
              <%= password_field_tag :password, nil, placeholder: 'password' %>
            </div></br>
            <div class="actions">
              <%= button_tag link_to "Cancel", root_path %>
              <%= button_tag "Log In", :class => 'submit-button'%>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <button class="btn btn-success"
              data-toggle="modal" data-target="#createUser" data-dismiss="modal">Sign Up</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>

</section>