config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  delete '/logout' => 'sessions#destroy'

  resources :dashboard
  resources :employments
  resources :events
  resources :friendships
  resources :profiles
  resources :sessions
  resources :users
  resources :searched

  resources :messages do
    resources :responses
  end

end

app/models/employment.rb
class Employment < ActiveRecord::Base
  belongs_to :profile
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
  has_many :messages
  has_many :events
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :friendship
  belongs_to :user

  # takes the time created_at and converts it into a readable date and time
  def created
   created_at.strftime('%m-%d-%Y %I:%M')
    
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # attr_accessible :city, :firstname, :lastname, :role

  belongs_to :user
  has_many :employments
  has_many :messages

  def full_name 
    "#{firstname} #{lastname}"
  end


  def self.search(search)
    if search
      where('city ILIKE ? OR firstname ILIKE ? OR lastname ILIKE ? OR role ILIKE ? OR company ILIKE?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      all
    end
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :message
  
  default_scope {order('created_at DESC')}

  # takes the time created_at and converts it to pacific standard time and then into a readable date and time
  def created
   created_at.in_time_zone("Pacific Time (US & Canada)").strftime('%m-%d-%Y %I:%M') 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :profile
  has_many :friendships
  has_many :friends, :through => :friendships, :class_name => "User"
  has_many :messages
  has_many :events
  # attr_accessor :email, :password, :password_confirmation
  validates_uniqueness_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# GET users/
  def index
    @users = User.all
    render :index
  end

# GET /users/id
  def show
  end

# GET /users/new
# creates user
  def new
    @user = User.new
  end

# POST /users
# saves user
  def create
    @user = User.new(user_params)
    @current_user = current_user
    if @user.save
      login(@user)
      create_profile @current_user.id
      add_default_image @user.profile
      redirect_to dashboard_index_path
    else
      render "new"
    end
  end

# GET /users/id/edit
  def edit
  end

# PATCH/PUT /users/id
  def update
  end

# DELETE /users/id
  def destroy
  end

  def create_profile user_id
    Profile.create(user_id: user_id)
  end

# make it private
  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def friend_request_accept
    # accepting a friend request is done by the recipient of the friend request.
    # thus the current user is identified by friend_id.
    friendship = Friendship.find(params[:id])
    friendship.update_attributes(status: 'confirm')
  end

  # def friend_delete
  #   friendship = Friendship.where(friend_id: current_user.id, user_id: params[:id]).first
  #   friendship.destroy
  # end

  def friend_request 
    @friendship.update_attribute(:status,'pending')
  end

  def friend_request_ignore
    friendship = Friendship.find(params[:id])
    @friendship.update_attribute(:status, 'ignore')
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

  def add_default_image profile
    profile.image = "profiledefault.jpg" if profile.image.blank?
    profile.save
  end
  
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/searched_helper.rb
module SearchedHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    session[:used_id] = user.id
    @current_user = user
  end

  def logged_in?
    if current_user == nil
    else
      true
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def current_user 
    @current_user ||= session[:user_id] && User.find(session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def friend_request
    user_id = current_user.id
    friend_id = params[:id] # this is the id of the user you want to become friend with
    friendship = Friendship.create(user_id: user_id, friend_id: friend_id, status: false)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="row">
    <div class="col-xs-12 center">
      <p id="footer-text"> Built in San Francisco. All rights reserved. &copy;2016 </p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default main-nav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <!-- pull code for hanburger css up top to change. -->
    <div class="navbar-header">
      <button type="button" id="hamburger" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span id="main-toggle" class="icon-bar"></span>
        <span id="main-toggle" class="icon-bar"></span>
        <span id="main-toggle" class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul id="center-nav" class="nav navbar-nav">
        <!-- <li class="active"><a href="/dashboard">Dashboard <span class="sr-only">(current)</span></a></li> -->
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="/profiles/">Search</a></li>
        <li><a href="/messages/">Messages</a></li>
        <li><%= link_to "Profile", profile_path(@current_user.profile.id) %></li>
        <li><a href="#">Account</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navhome.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" id="hamburger" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if logged_in? %>
        <a class="navbar-brand" href="/dashboard/">ReferMe</a>
      <% else %>
        <a class="navbar-brand" href="/">ReferMe</a>
      <% end %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <% @user = current_user %>
          <!-- <li><a href="/dashboard/"><%= "Welcome #{@user.profile.firstname}" %></a></li> -->
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
      <% else %>
        <li ><%= link_to "Login", "#", data: {toggle: "modal", target: "#logUser"} %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Refer Me</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller], 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.jpg' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= render partial: "./layouts/navhome" %>
<% if !(current_page?(controller:'welcome', action:'index'))%>
  <%=render partial: "./layouts/navbar"%>
<%end%>
<%= yield %>
<%=render partial: "./layouts/footer"%>
</body>
</html>